# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sohyeon/다운로드/Lgorithm-main/design_recom.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 671)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 60, 621, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_prod = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_prod.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.grid_prod.setContentsMargins(0, 0, 0, 0)
        self.grid_prod.setObjectName("grid_prod")
        self.cust_cnt = QtWidgets.QLabel(Dialog)
        self.cust_cnt.setGeometry(QtCore.QRect(490, 20, 56, 12))
        self.cust_cnt.setText("")
        self.cust_cnt.setAlignment(QtCore.Qt.AlignCenter)
        self.cust_cnt.setObjectName("cust_cnt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
